#!/system/bin/sh
if [ -e /sys/class/misc/gpu_clock_control/gpu_control ]; then
	echo "100 200 267" > /sys/class/misc/gpu_clock_control/gpu_control;
	echo "85% 45% 85% 70%" > /sys/class/misc/gpu_clock_control/gpu_control;
	#echo "800000 850000 950000" > /sys/devices/virtual/misc/gpu_voltage_control/gpu_control;
fi;
#if [ -e  /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
	#echo "1400 1300 1175 1075 975 850 825 825 " > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table;
#fi;
