#!/system/bin/sh
sync;
echo 3 > /proc/sys/vm/drop_caches;
sleep 1;
echo 0 > /proc/sys/vm/drop_caches;
echo "Caches are dropped!";
echo 500000 > /proc/sys/kernel/sched_min_granularity_ns;
echo 2500000 > /proc/sys/kernel/sched_latency_ns;
echo 500000 > /proc/sys/kernel/sched_wakeup_granularity_ns;
